apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developers
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - delete
